travis:
  secure:
    BINSTAR_TOKEN: gyyzfRWX2j7OwjDdNWkHq1DUOFhIttZ83d12r1D0bJQ/ROH6CeirqAG/iqDJeBmqbtArVr4lLI8AskMxYbQ/O3I7JagJy+dBBq8EFhmhHtCjXzbsoNdre23aFJG1q09vno+hhALOKWKjVd61pDkydEyyfweGttGm5TPp6EN2k6SQOXcm8AgQUJEE80QkatmNbiY6jtLhccVGfFvvYS6N0LObtTrAkW3Gnw8YBhY1MDUdRCMZFkMO0vOMWe4jS5BpqHXcUUcNSG9Dlpji/Rnyka8VcnQEsjyLiYNYNLvkhpt8R+EpDVIzyMhFXUUErKYljbP3lP1uZIOxEpwe3bX+fk1deEyAfSSAn7CP3dumAUH7fBVHzksz1SBQn/cV2bJErJ7KmWGTXKN/QwEF450h7JOIam+sXTCowvZqiGU7H6VKawdTHk+G2Hqp63nGDhUh/hM1lNfcdACmAqJAfukupWCe6Wpew5NzXMPNK+uMp8BH4YPHRAXonpUcAG+pRg8FrIjQtD5Eu9h8l04jal+AD29c6mKwMPZDXqyo0b/npBGzdXMpnRMCLn/fxXlmDpdj6V9kCXv5rZAUH9Hr5My+uEKF2gjZ/oJJzokALkWK7lpnno4r7MmB5dfSBigJBu8u8UTzditmwrM9axSCEeatmTamZSnc/ZDwPTAej758ARM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
